!!AA_SEQUENCE 1.0
gi|47565|emb|CAA45795.1| DNA-directed DNA polymerase [Sulfolobus solfataricus]

gi-47565.pep  Length: 882  July 19, 2002 10:26  Type: P  Check: 2452  ..

       1  MTKQLTLFDI PSSKPAKSEQ NTQQSQQSAP VEEKKVVRRE WLEEAQENKI 

      51  YFLLQVDYDG KKGKAVCKLF DKETQKIYAL YDNTGHKPYF LVDLEPDKVG 

     101  KIPKIVRDPS FDHIETVSKI DPYTWNKFKL TKIVVRDPHA VRRLRNDVPK 

     151  AYEAHIKYFN NYMYDIGLIP GMPYVVKNGK LESVYLSLDE KDVEEIKKAF 

     201  ADSDEMTRQM AVDWLPIFET EIPKIKRVAI DIEVYTPVKG RIPDSQKAEF 

     251  PIISIALAGS DGLKKVLVLN RNDVNEGSVK LDGISVERFN TEYELLGRFF 

     301  DILLEYPIVL TFNGDDFDLP YIYFRALKLG YFPEEIPIDV AGKDEAKYLA 

     351  GLHIDLYKFF FNKAVRNYAF EGKYNEYNLD AVAKALLGTS KVKVDTLISF 

     401  LDVEKLIEYN FRDAEITLQL TTFNNDLTMK LIVLFSRISR LGIEELTRTE 

     451  ISTWVKNLYY WEHRKRNWLI PLKEEILAKS SNIRTSALIK GKGYKGAVVI 

     501  DPPAGIFFNI TVLDFASLYP SIIRTWNLSY ETVDIQQCKK PYEVKDETGE 

     551  VLHIVCMDRP GITAVITGLL RDFRVKIYKK KAKNPNNSEE QKLLYDVVQR 

     601  AMKVFINATY GVFGAETFPL YAPRVAESVT ALGRYVITST VKKAREEGLT 

     651  VLYGDTDSLF LLNPPKNSLE NIIKWVKTTF NLDLEVDKTY KFVAFSGLKK 

     701  NYFGVYQDGK VDIKGMLVKK RNTPEFVKKV FNEVKELMIS INSPNDVKEI 

     751  KRKIVDVVKG SYEKLKNKGY NLDELAFKVM LSKPLDAYKK NTPQHVKAAL 

     801  QLRPFGVNVL PRDIIYYVKV RSKDGVKPVQ LAKVTEIDAE KYLEALRSTF 

     851  EQILRAFGVS WDEIAATMSI DSFFSYPSKG NS


