>P1;GI-47565
gi-47565.pep => GI-47565
          MTKQLTLFDI PSSKPAKSEQ NTQQSQQSAP VEEKKVVRRE WLEEAQENKI 
          YFLLQVDYDG KKGKAVCKLF DKETQKIYAL YDNTGHKPYF LVDLEPDKVG 
          KIPKIVRDPS FDHIETVSKI DPYTWNKFKL TKIVVRDPHA VRRLRNDVPK 
          AYEAHIKYFN NYMYDIGLIP GMPYVVKNGK LESVYLSLDE KDVEEIKKAF 
          ADSDEMTRQM AVDWLPIFET EIPKIKRVAI DIEVYTPVKG RIPDSQKAEF 
          PIISIALAGS DGLKKVLVLN RNDVNEGSVK LDGISVERFN TEYELLGRFF 
          DILLEYPIVL TFNGDDFDLP YIYFRALKLG YFPEEIPIDV AGKDEAKYLA 
          GLHIDLYKFF FNKAVRNYAF EGKYNEYNLD AVAKALLGTS KVKVDTLISF 
          LDVEKLIEYN FRDAEITLQL TTFNNDLTMK LIVLFSRISR LGIEELTRTE 
          ISTWVKNLYY WEHRKRNWLI PLKEEILAKS SNIRTSALIK GKGYKGAVVI 
          DPPAGIFFNI TVLDFASLYP SIIRTWNLSY ETVDIQQCKK PYEVKDETGE 
          VLHIVCMDRP GITAVITGLL RDFRVKIYKK KAKNPNNSEE QKLLYDVVQR 
          AMKVFINATY GVFGAETFPL YAPRVAESVT ALGRYVITST VKKAREEGLT 
          VLYGDTDSLF LLNPPKNSLE NIIKWVKTTF NLDLEVDKTY KFVAFSGLKK 
          NYFGVYQDGK VDIKGMLVKK RNTPEFVKKV FNEVKELMIS INSPNDVKEI 
          KRKIVDVVKG SYEKLKNKGY NLDELAFKVM LSKPLDAYKK NTPQHVKAAL 
          QLRPFGVNVL PRDIIYYVKV RSKDGVKPVQ LAKVTEIDAE KYLEALRSTF 
          EQILRAFGVS WDEIAATMSI DSFFSYPSKG NS*
C;gi|47565|emb|CAA45795.1| DNA-directed DNA polymerase [Sulfolobus solfataricus]


